import type { Locale } from "./config";

export type FormCopy = {
  combo: string; from: string; to: string; address: string; details: string;
  name: string; phone: string; date: string; photos: string; privacy: string;
  submit: string; successTitle: string; successDescription: string; again: string;
};

const en: FormCopy = { combo: "Moving + cleaning", from: "From address", to: "Destination address", address: "Service address", details: "Details", name: "Your name", phone: "Phone number", date: "Preferred date", photos: "Photos (optional)", privacy: "I consent to the processing of my data for this request.", submit: "Send request", successTitle: "Thank you! We received your request.", successDescription: "We will contact you shortly to confirm the details.", again: "Send another request" };

export const formCopy: Record<Locale, FormCopy> = {
  uk: { combo: "Переїзд + прибирання", from: "Адреса відправлення", to: "Адреса призначення", address: "Адреса виконання", details: "Деталі замовлення", name: "Ваше ім’я", phone: "Номер телефону", date: "Бажана дата", photos: "Фотографії (необов’язково)", privacy: "Я погоджуюся на обробку даних для підготовки пропозиції.", submit: "Надіслати запит", successTitle: "Дякуємо! Ми отримали ваш запит.", successDescription: "Незабаром ми зв’яжемося з вами та уточнимо деталі.", again: "Надіслати ще один запит" },
  en,
  de: { combo: "Umzug + Reinigung", from: "Startadresse", to: "Zieladresse", address: "Einsatzadresse", details: "Auftragsdetails", name: "Ihr Name", phone: "Telefonnummer", date: "Wunschtermin", photos: "Fotos (optional)", privacy: "Ich stimme der Verarbeitung meiner Daten für diese Anfrage zu.", submit: "Anfrage senden", successTitle: "Vielen Dank! Ihre Anfrage ist eingegangen.", successDescription: "Wir melden uns in Kürze, um die Details zu klären.", again: "Weitere Anfrage senden" },
  fr: { combo: "Déménagement + nettoyage", from: "Adresse de départ", to: "Adresse de destination", address: "Adresse du service", details: "Détails de la demande", name: "Votre nom", phone: "Téléphone", date: "Date souhaitée", photos: "Photos (facultatif)", privacy: "J’accepte le traitement de mes données pour cette demande.", submit: "Envoyer la demande", successTitle: "Merci ! Nous avons reçu votre demande.", successDescription: "Nous vous contacterons bientôt pour confirmer les détails.", again: "Envoyer une autre demande" },
  it: { combo: "Trasloco + pulizia", from: "Indirizzo di partenza", to: "Indirizzo di destinazione", address: "Indirizzo del servizio", details: "Dettagli della richiesta", name: "Nome", phone: "Telefono", date: "Data preferita", photos: "Foto (facoltative)", privacy: "Acconsento al trattamento dei dati per questa richiesta.", submit: "Invia richiesta", successTitle: "Grazie! Abbiamo ricevuto la richiesta.", successDescription: "Ti contatteremo presto per confermare i dettagli.", again: "Invia un’altra richiesta" },
  et: { ...en, combo: "Kolimine + koristus", name: "Teie nimi", phone: "Telefon", date: "Soovitud kuupäev", privacy: "Nõustun oma andmete töötlemisega selle päringu jaoks.", submit: "Saada päring", successTitle: "Aitäh! Saime teie päringu kätte." },
  pl: { combo: "Przeprowadzka + sprzątanie", from: "Adres początkowy", to: "Adres docelowy", address: "Adres usługi", details: "Szczegóły zlecenia", name: "Imię", phone: "Telefon", date: "Preferowany termin", photos: "Zdjęcia (opcjonalnie)", privacy: "Wyrażam zgodę na przetwarzanie danych w celu obsługi zapytania.", submit: "Wyślij zapytanie", successTitle: "Dziękujemy! Otrzymaliśmy zapytanie.", successDescription: "Wkrótce skontaktujemy się, aby potwierdzić szczegóły.", again: "Wyślij kolejne zapytanie" },
  lt: { ...en, combo: "Persikraustymas + valymas", name: "Jūsų vardas", phone: "Telefonas", date: "Pageidaujama data", privacy: "Sutinku, kad mano duomenys būtų tvarkomi dėl šios užklausos.", submit: "Siųsti užklausą", successTitle: "Ačiū! Gavome jūsų užklausą." },
  lv: { ...en, combo: "Pārcelšanās + uzkopšana", name: "Jūsu vārds", phone: "Tālrunis", date: "Vēlamais datums", privacy: "Piekrītu datu apstrādei šī pieprasījuma vajadzībām.", submit: "Nosūtīt pieprasījumu", successTitle: "Paldies! Pieprasījums ir saņemts." },
  cs: { ...en, combo: "Stěhování + úklid", from: "Adresa odkud", to: "Cílová adresa", address: "Adresa služby", details: "Podrobnosti", name: "Vaše jméno", phone: "Telefon", date: "Požadovaný termín", photos: "Fotografie (volitelné)", privacy: "Souhlasím se zpracováním údajů pro tuto poptávku.", submit: "Odeslat poptávku", successTitle: "Děkujeme! Poptávku jsme přijali.", successDescription: "Brzy vás kontaktujeme.", again: "Odeslat další poptávku" },
  es: { ...en, combo: "Mudanza + limpieza", from: "Dirección de origen", to: "Dirección de destino", address: "Dirección del servicio", details: "Detalles", name: "Nombre", phone: "Teléfono", date: "Fecha preferida", photos: "Fotos (opcional)", privacy: "Acepto el tratamiento de mis datos para esta solicitud.", submit: "Enviar solicitud", successTitle: "¡Gracias! Hemos recibido su solicitud.", successDescription: "Nos pondremos en contacto pronto.", again: "Enviar otra solicitud" },
  tr: { ...en, combo: "Taşınma + temizlik", name: "Adınız", phone: "Telefon", date: "Tercih edilen tarih", privacy: "Bu talep için verilerimin işlenmesini kabul ediyorum.", submit: "Talep gönder", successTitle: "Teşekkürler! Talebinizi aldık." },
  ar: { combo: "الانتقال + التنظيف", from: "عنوان الانطلاق", to: "عنوان الوجهة", address: "عنوان الخدمة", details: "تفاصيل الطلب", name: "الاسم", phone: "رقم الهاتف", date: "التاريخ المفضل", photos: "صور (اختياري)", privacy: "أوافق على معالجة بياناتي لهذا الطلب.", submit: "إرسال الطلب", successTitle: "شكرًا! استلمنا طلبك.", successDescription: "سنتواصل معك قريبًا لتأكيد التفاصيل.", again: "إرسال طلب آخر" },
  "nl-BE": { ...en, combo: "Verhuizen + schoonmaak", name: "Uw naam", phone: "Telefoon", date: "Gewenste datum", privacy: "Ik stem in met de verwerking van mijn gegevens voor deze aanvraag.", submit: "Aanvraag verzenden", successTitle: "Bedankt! We hebben uw aanvraag ontvangen." },
  sk: { ...en, combo: "Sťahovanie + upratovanie", name: "Vaše meno", phone: "Telefón", date: "Požadovaný termín", privacy: "Súhlasím so spracovaním údajov pre túto žiadosť.", submit: "Odoslať žiadosť", successTitle: "Ďakujeme! Žiadosť sme prijali." },
  hu: { ...en, combo: "Költözés + takarítás", name: "Az Ön neve", phone: "Telefon", date: "Kívánt időpont", privacy: "Hozzájárulok adataim kezeléséhez ehhez a kéréshez.", submit: "Kérés küldése", successTitle: "Köszönjük! Megkaptuk a kérését." },
  ro: { ...en, combo: "Mutare + curățenie", name: "Numele dvs.", phone: "Telefon", date: "Data preferată", privacy: "Sunt de acord cu prelucrarea datelor pentru această cerere.", submit: "Trimite cererea", successTitle: "Mulțumim! Am primit cererea." },
  sr: { ...en, combo: "Селидба + чишћење", name: "Ваше име", phone: "Телефон", date: "Жељени датум", privacy: "Пристајем на обраду података за овај захтев.", submit: "Пошаљи захтев", successTitle: "Хвала! Примили смо ваш захтев." },
  bg: { ...en, combo: "Преместване + почистване", name: "Вашето име", phone: "Телефон", date: "Желана дата", privacy: "Съгласявам се с обработката на данните за тази заявка.", submit: "Изпрати заявка", successTitle: "Благодарим! Получихме заявката." },
};
