import type { Locale } from "./config";

const descriptions: Record<Locale, string> = {
  uk: "Плануєте переїзд, доставку великої покупки чи потребуєте допомоги вдома? Ми дбайливо перевеземо речі, доставимо меблі й техніку, зберемо меблі, виконаємо дрібні електричні роботи та приберемо житло. Ви отримуєте одну надійну команду, заздалегідь узгоджені умови й акуратний результат без зайвого клопоту.",
  en: "Planning a move, a large delivery or need help at home? We carefully transport belongings, deliver furniture and appliances, assemble furniture, handle minor electrical jobs and clean your home. You get one reliable team, clear terms agreed in advance and a careful result without unnecessary stress.",
  de: "Planen Sie einen Umzug, eine grössere Lieferung oder brauchen Sie Hilfe zu Hause? Wir transportieren Ihre Sachen sorgfältig, liefern Möbel und Geräte, montieren Möbel, erledigen kleine Elektroarbeiten und reinigen Ihre Wohnung. Sie erhalten ein zuverlässiges Team, vorab vereinbarte Bedingungen und ein sauberes Ergebnis ohne unnötigen Aufwand.",
  fr: "Vous préparez un déménagement, une livraison volumineuse ou avez besoin d’aide à domicile ? Nous transportons vos biens avec soin, livrons meubles et appareils, montons le mobilier, réalisons de petits travaux électriques et nettoyons votre logement. Une seule équipe fiable, des conditions claires convenues à l’avance et un résultat soigné sans stress inutile.",
  it: "State organizzando un trasloco, una consegna ingombrante o avete bisogno di aiuto in casa? Trasportiamo con cura i vostri beni, consegniamo mobili ed elettrodomestici, montiamo mobili, svolgiamo piccoli lavori elettrici e puliamo l’abitazione. Un’unica squadra affidabile, condizioni chiare concordate in anticipo e un risultato accurato senza stress.",
  et: "Kas plaanite kolimist, suurt tarnet või vajate kodus abi? Veame teie asju hoolikalt, tarnime mööblit ja tehnikat, paneme mööbli kokku, teeme väiksemaid elektritöid ning koristame kodu. Saate ühe usaldusväärse meeskonna, ette kokkulepitud tingimused ja korraliku tulemuse ilma liigse mureta.",
  pl: "Planujesz przeprowadzkę, dużą dostawę albo potrzebujesz pomocy w domu? Ostrożnie przewieziemy rzeczy, dostarczymy meble i sprzęt, złożymy meble, wykonamy drobne prace elektryczne i posprzątamy mieszkanie. Otrzymujesz jeden zaufany zespół, warunki ustalone z wyprzedzeniem i staranny rezultat bez zbędnego stresu.",
  lt: "Planuojate persikraustymą, didelį pristatymą ar reikia pagalbos namuose? Atsargiai pervešime daiktus, pristatysime baldus ir techniką, surinksime baldus, atliksime smulkius elektros darbus ir sutvarkysime būstą. Viena patikima komanda, iš anksto suderintos sąlygos ir kruopštus rezultatas be nereikalingų rūpesčių.",
  lv: "Plānojat pārvākšanos, lielu piegādi vai nepieciešama palīdzība mājās? Rūpīgi pārvedīsim mantas, piegādāsim mēbeles un tehniku, saliksim mēbeles, veiksim nelielus elektrības darbus un uzkopsim mājokli. Viena uzticama komanda, iepriekš saskaņoti nosacījumi un rūpīgs rezultāts bez liekām raizēm.",
  cs: "Plánujete stěhování, větší dovoz nebo potřebujete pomoc doma? Pečlivě převezeme věci, dovezeme nábytek a spotřebiče, smontujeme nábytek, provedeme drobné elektropráce a uklidíme bydlení. Získáte jeden spolehlivý tým, podmínky dohodnuté předem a pečlivý výsledek bez zbytečných starostí.",
  es: "¿Está planeando una mudanza, una entrega grande o necesita ayuda en casa? Transportamos sus pertenencias con cuidado, entregamos muebles y electrodomésticos, montamos muebles, realizamos pequeños trabajos eléctricos y limpiamos su vivienda. Un único equipo de confianza, condiciones acordadas de antemano y un resultado cuidado sin estrés innecesario.",
  tr: "Taşınma, büyük bir teslimat mı planlıyorsunuz ya da evde yardıma mı ihtiyacınız var? Eşyalarınızı özenle taşıyor, mobilya ve cihazları teslim ediyor, mobilyaları kuruyor, küçük elektrik işleri yapıyor ve evinizi temizliyoruz. Tek bir güvenilir ekip, önceden kararlaştırılmış açık koşullar ve gereksiz stres olmadan özenli bir sonuç.",
  ar: "هل تخطط للانتقال أو لتوصيل مشتريات كبيرة أو تحتاج إلى مساعدة في المنزل؟ ننقل أغراضك بعناية، ونوصل الأثاث والأجهزة، ونركب الأثاث، وننفذ الأعمال الكهربائية البسيطة، وننظف المنزل. تحصل على فريق واحد موثوق، وشروط واضحة متفق عليها مسبقاً، ونتيجة متقنة من دون عناء غير ضروري.",
  "nl-BE": "Plant u een verhuizing, een grote levering of hebt u hulp nodig in huis? We vervoeren uw spullen zorgvuldig, leveren meubels en toestellen, monteren meubels, voeren kleine elektriciteitswerken uit en reinigen uw woning. U krijgt één betrouwbaar team, vooraf afgesproken voorwaarden en een verzorgd resultaat zonder onnodige stress.",
  sk: "Plánujete sťahovanie, väčšiu dodávku alebo potrebujete pomoc doma? Starostlivo prevezieme veci, dovezieme nábytok a spotrebiče, zmontujeme nábytok, vykonáme drobné elektropráce a upraceme bývanie. Získate jeden spoľahlivý tím, podmienky dohodnuté vopred a dôkladný výsledok bez zbytočných starostí.",
  hu: "Költözést, nagyobb kiszállítást tervez, vagy segítségre van szüksége otthon? Gondosan szállítjuk a holmikat, bútorokat és gépeket viszünk ki, bútort szerelünk, kisebb villanyszerelési munkákat végzünk és kitakarítjuk az otthont. Egy megbízható csapat, előre egyeztetett feltételek és gondos eredmény felesleges stressz nélkül.",
  ro: "Planificați o mutare, o livrare voluminoasă sau aveți nevoie de ajutor acasă? Transportăm cu grijă bunurile, livrăm mobilier și electrocasnice, montăm mobilier, efectuăm lucrări electrice mici și curățăm locuința. Aveți o singură echipă de încredere, condiții stabilite în avans și un rezultat atent, fără stres inutil.",
  sr: "Планирате селидбу, велику доставу или вам је потребна помоћ у дому? Пажљиво превозимо ствари, достављамо намештај и уређаје, монтирамо намештај, обављамо ситне електричарске радове и чистимо дом. Добијате један поуздан тим, унапред договорене услове и уредан резултат без непотребног стреса.",
  bg: "Планирате преместване, голяма доставка или имате нужда от помощ у дома? Превозваме вещите внимателно, доставяме мебели и уреди, сглобяваме мебели, извършваме дребни електрически работи и почистваме жилището. Получавате един надежден екип, предварително уговорени условия и прецизен резултат без излишни грижи.",
};

export function getHeroDescription(locale: Locale) {
  return descriptions[locale];
}
